import { ethers } from 'ethers';
import { Facilitator } from '@crypto.com/facilitator-client';

export interface RWAConfig {
    apiUrl: string;
    facilitatorAddress?: string;
    provider?: ethers.BrowserProvider | ethers.JsonRpcProvider;
}

export interface RWAStateMachine {
    id: string;
    rwaId: string;
    currentState: string;
    previousState: string | null;
    metadata: Record<string, unknown>;
    createdAt: string;
    updatedAt: string;
}

export interface TransitionParams {
    rwaId: string;
    toState: string;
    agentAddress: string;
    agentRole: string;
    signer: ethers.Signer;
}

export interface TransitionResult {
    success: boolean;
    txHash?: string;
    newState?: string;
    error?: string;
}

/**
 * RelayRWASDK - SDK for managing Real-World Asset (RWA) state machines
 * with x402 payment enforcement and agent coordination.
 */
export class RelayRWASDK {
    private config: RWAConfig;

    constructor(config: RWAConfig) {
        this.config = config;
    }

    /**
     * Create a new RWA state machine
     */
    async create(rwaId: string, metadata: Record<string, unknown> = {}): Promise<RWAStateMachine> {
        const response = await fetch(`${this.config.apiUrl}/api/rwa/state-machine/create`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ rwaId, metadata })
        });

        if (!response.ok) {
            throw new Error(`Failed to create RWA: ${response.statusText}`);
        }

        return await response.json();
    }

    /**
     * Get RWA state by ID
     */
    async getState(rwaId: string): Promise<RWAStateMachine> {
        const response = await fetch(`${this.config.apiUrl}/api/rwa/state-machine/${rwaId}/state`);

        if (!response.ok) {
            throw new Error(`Failed to get RWA state: ${response.statusText}`);
        }

        return await response.json();
    }

    /**
     * Transition RWA state with x402 payment enforcement
     */
    async transition(params: TransitionParams): Promise<TransitionResult> {
        const { rwaId, toState, agentAddress, agentRole, signer } = params;

        // Step 1: Request transition (expecting 402)
        const initResponse = await fetch(`${this.config.apiUrl}/api/rwa/state-machine/${rwaId}/transition`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ rwaId, toState, agentAddress, agentRole })
        });

        if (initResponse.status !== 402) {
            const data = await initResponse.json();
            return { success: true, newState: data.newState, txHash: data.txHash };
        }

        // Step 2: Handle x402 Payment
        const paymentRequirements = initResponse.headers.get('XXX-Payment-Config');
        if (!paymentRequirements) {
            throw new Error('No payment requirements received');
        }

        const requirements = JSON.parse(paymentRequirements);

        // Generate EIP-3009 signature using Facilitator Client logic
        // Note: In a real SDK bundle, this would use a properly instantiated Facilitator
        // For now, we simulate the client-side signing flow

        const signerAddress = await signer.getAddress();
        const facilitator = new Facilitator(requirements.payTo); // simplified

        // This is a placeholder for the actual SDK signing logic which might vary
        // depending on the environment (browser vs node)
        // In a real implementation, we'd reuse the logic from verify-payment.ts

        // For production use, we assume the user provides a payment header
        // generated by the Facilitator client separately if needed,
        // or we implement the full signing here.

        // TO DO: Full client-side signing implementation
        // For now, we return specific instructions
        throw new Error('SDK requires a fully initialized Facilitator instance for automatic payment signing. Please use the UI or CLI.');
    }
}

/**
 * Create a new RWA SDK instance
 */
export function createRWASDK(config: RWAConfig): RelayRWASDK {
    return new RelayRWASDK(config);
}
